spring.application.name=petcare

server.port=8080

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/petcare_db
spring.datasource.username=petcare_user
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# FLYWAY
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=false

# THYMELEAF
spring.thymeleaf.cache=false
# ===============================
# DEFAULT ADMIN - DEVELOPMENT ONLY
# ===============================

app.admin.username=admin
app.admin.password=Admin@123

# ===============================
# GOOGLE GEMINI AI (VIRTUAL VET)
# ===============================
# Lấy API Key miễn phí tại: https://aistudio.google.com/
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.model=gemini-2.5-flash

# ===============================
# GMAIL SMTP CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hcnhat0804@gmail.com
spring.mail.password=xvbntmvebcbkpnau
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.base-url=http://localhost:8080

