spring.application.name=petcare

server.port=8080

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/petcare_db
spring.datasource.username=petcare_user
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# FLYWAY
spring.flyway.enabled=true

# THYMELEAF
spring.thymeleaf.cache=false
# ===============================
# DEFAULT ADMIN - DEVELOPMENT ONLY
# ===============================

app.admin.username=admin
app.admin.password=Admin@123

# ===============================
# GOOGLE GEMINI AI (VIRTUAL VET)
# ===============================
# Lấy API Key miễn phí tại: https://aistudio.google.com/
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.model=gemini-2.5-flash

